language: java

jdk:
  - oraclejdk8
  - openjdk8

script: mvn cobertura:cobertura sonar:sonar -Dsonar.organization=javydreamercsw-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=6e3a9d4d7b11e581b919b9ba1498f02ac35a3fa8

after_success:
  - bash <(curl -s https://codecov.io/bash)
